---
- name: Download HashiCorp GPG key and save it
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /tmp/hashicorp.gpg
    mode: '0600'

- name: Ensure keyrings directory exists with correct permissions
  ansible.builtin.file:
    path: /usr/share/keyrings
    state: directory
    mode: '0755'

- name: Convert HashiCorp GPG key to keyring
  ansible.builtin.command:
    cmd: gpg --dearmor -o /usr/share/keyrings/hashicorp-archive-keyring.gpg /tmp/hashicorp.gpg
    creates: /usr/share/keyrings/hashicorp-archive-keyring.gpg

- name: Set permissions for HashiCorp keyring
  ansible.builtin.file:
    path: /usr/share/keyrings/hashicorp-archive-keyring.gpg
    mode: '0644'

- name: Ensure the HashiCorp sources list file exists with correct permissions
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/hashicorp.list
    state: touch
    mode: '0644'

- name: Add HashiCorp APT repository
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/hashicorp.list
    line: "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com {{ ansible_facts.lsb.codename }} main"
    create: true

- name: Set permissions and ownership for HashiCorp sources list file
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/hashicorp.list
    mode: '0644'
    owner: root
    group: root

- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true

- name: Install Terraform
  ansible.builtin.apt:
    name: terraform
    state: present
