- name: Download AWS CLI v2 installer
  ansible.builtin.get_url:
    url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
    dest: /tmp/awscliv2.zip

- name: Set permissions for AWS CLI installer
  ansible.builtin.file:
    path: /tmp/awscliv2.zip
    mode: '0644'

- name: Install unzip package
  ansible.builtin.apt:
    name: unzip
    state: present

- name: Unzip AWS CLI installer
  ansible.builtin.unarchive:
    src: /tmp/awscliv2.zip
    dest: /tmp/
    remote_src: true

- name: Set permissions for unzipped files
  ansible.builtin.file:
    path: /tmp/aws/
    state: directory
    mode: '0755'

- name: Install AWS CLI v2
  ansible.builtin.command:
    cmd: /tmp/aws/install
    creates: /usr/local/bin/aws
