apiVersion: apps/v1
kind: Deployment
metadata: 
  namespace: {{ .Values.common.namespace }}
  name: {{ .Values.mongodb.name }}
  annotations:
    "helm.sh/hook": pre-install
spec: 
  replicas: {{ .Values.mongodb.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.mongodb.name }}
  template:
    metadata:
      labels: 
        app: {{ .Values.mongodb.name }}
    spec: 
      containers:
      - name: mon
        image: "{{ .Values.mongodb.image.name }}:{{ .Values.mongodb.image.version }}"
        command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--wiredTigerCacheSizeGB"
            - "0.1"
            - "--bind_ip"
            - "0.0.0.0"
        ports:
        - containerPort: {{ .Values.mongodb.containerPort }}
        env: 
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: username
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-sec
                key: password
        volumeMounts:
          - name: mongo-volume
            mountPath: {{ .Values.mongodb.pv.storagepath }}
      volumes: 
      - name: mongo-volume
        persistentVolumeClaim:
          claimName: {{ .Values.mongodb.pvc.name }}