---
- name: Update APT package index
  ansible.builtin.apt:
    update_cache: true

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: present

- name: Download kubectl binary
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v1.28.4/bin/linux/amd64/kubectl"
    dest: /tmp/kubectl
    mode: '0755'

- name: Ensure kubectl binary is in /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/kubectl
    dest: /usr/local/bin/kubectl
    mode: '0755'
    remote_src: yes
