####--------Common-Values--------######

common:
  namespace: mern-stack

####--------Database-Values-------######

mongodb:
  name: mongo
  replicas: 1
  image:
    name: mongodb
    version: 4.4.6
  containerPort: 27017
  pvc:
    name: mongo-volume-claim
    storage: 1Gi