- name: Start SonarQube container
  community.docker.docker_container:
    name: sonar
    image: sonarqube:lts-community
    state: started
    restart_policy: always
    published_ports:
    - "9000:9000"
